const { _electron:electron }=require('playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert');
const root=path.resolve(__dirname,'../..'),fixture=fs.mkdtempSync(path.join(os.tmpdir(),'smart-organizer-v2-')),output=path.join(root,'build','smart-ui-qa');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const desktop=await electron.launch({executablePath:require('electron'),args:[path.join(root,'frontend/electron/main.cjs'),`--state-dir=${path.join(fixture,'state')}`],env:{...process.env,SMART_UI_FIXTURE:fixture,SMART_ENGINE_SCRIPT:path.join(root,'tests/fixture_rpc.py'),SMART_PYTHON:process.env.SMART_QA_PYTHON||'python'}});
 const page=await desktop.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(String(e)));
 try{
  await page.getByRole('button',{name:'Scan Computer',exact:true}).waitFor();await page.waitForFunction(()=>window.organizer&&document.body.innerText.includes('File Organizer'));await page.screenshot({path:path.join(output,'home.png'),fullPage:true});
  // A native approval prompt is a V2 regression; never mock it to accept.
  await desktop.evaluate(({dialog})=>{dialog.showMessageBox=async()=>{throw Error('Unexpected mandatory confirmation');};});
  await page.getByRole('button',{name:'Scan Computer',exact:true}).click();await page.getByRole('button',{name:'Pause Scan',exact:true}).click();await page.getByRole('button',{name:'Resume Scan',exact:true}).waitFor();await page.screenshot({path:path.join(output,'scan.png'),fullPage:true});await page.getByRole('button',{name:'Resume Scan',exact:true}).click();await page.getByRole('button',{name:'Organize Files',exact:true}).waitFor({timeout:30000});await page.screenshot({path:path.join(output,'scan-result.png'),fullPage:true});
  assert.strictEqual(await page.getByRole('checkbox').count(),0);await page.getByRole('button',{name:'View Details',exact:true}).click();assert(await page.getByText('EEE101_Lecture_03.pdf',{exact:false}).count());await page.getByRole('button',{name:'Close dialog'}).click();
  await page.getByRole('button',{name:'Organize Files',exact:true}).click();await page.getByRole('button',{name:'Done',exact:true}).waitFor({timeout:30000});assert(await page.getByRole('button',{name:'View Word Report',exact:true}).isEnabled());await page.screenshot({path:path.join(output,'result.png'),fullPage:true});
  await desktop.evaluate(({shell})=>{shell.openPath=async target=>{global.__openedLibrary=target;return '';};});await page.getByRole('button',{name:'Open Organized Files',exact:true}).click();let opened;for(let n=0;n<100;n++){opened=await desktop.evaluate(()=>global.__openedLibrary);if(opened)break;await new Promise(r=>setTimeout(r,20));}assert.strictEqual(opened,path.join(fixture,'File Library'));
  assert(fs.existsSync(path.join(fixture,'File Library','Review Before Delete','Confirmed Duplicates')));assert(fs.existsSync(path.join(fixture,'Downloads','Website','assets','logo.png')));assert(fs.existsSync(path.join(fixture,'Downloads','manual.xyz')));assert(fs.existsSync(path.join(fixture,'File Library','Education','EEE101','Lectures','EEE101_Lecture_03.pdf')));
  await page.getByRole('button',{name:'Undo Organization',exact:true}).click();await page.getByText('Your originals are back.',{exact:true}).waitFor({timeout:30000});assert(fs.existsSync(path.join(fixture,'Downloads','EEE101 Lecture(3)final.pdf')));assert(fs.existsSync(path.join(fixture,'Downloads','invoice-final-new2.pdf')));assert(fs.existsSync(path.join(fixture,'Downloads','ChromeSetup.exe')));
  await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('checkbox',{name:'Automatic rename',exact:true}).click();await page.waitForFunction(()=>document.querySelector('input[aria-label="Automatic rename"]')?.checked===false);await page.waitForFunction(()=>!document.querySelector('.progress-backdrop'));assert.strictEqual(await page.evaluate(async()=>(await window.organizer.snapshot()).settings.automatic_rename),false);await page.getByRole('combobox',{name:'Theme'}).selectOption('dark');await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.getByRole('combobox',{name:'Theme'}).selectOption('light');await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.getByRole('button',{name:'Close dialog'}).click();
  assert.strictEqual(errors.length,0);fs.writeFileSync(path.join(root,'docs','smart-desktop-test.json'),JSON.stringify({passed:true,checks:['automatic discovery','two-click workflow','no mandatory approval dialog','optional details','automatic rename','project integrity','unknown unchanged','automatic quarantine','open correct library','DOCX generated','complete session Undo','rename setting','theme setting'],renderer_errors:errors,synthetic_only:true},null,2));console.log('V2 DESKTOP E2E PASSED');
 }finally{await desktop.close();assert(path.dirname(path.resolve(fixture))===path.resolve(os.tmpdir())&&path.basename(fixture).startsWith('smart-organizer-v2-'));fs.rmSync(fixture,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
