import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Layers,ShieldCheck,ScanLine,ArrowRight,Settings2,FileText,FolderOpen,CheckCircle2,Undo2,Clock3,X,Pause,Play,LoaderCircle,HardDrive,Search,Check,Sparkles,Image as ImageIcon} from 'lucide-react';
import type {Snapshot,Progress} from './types';
import './styles.css';
const empty:Snapshot={storage:[],ready:false,cancelled:false,plan_count:0,settings:{folders:[],library:'',ignored:[],excluded_drives:[],external_drives:true,automatic_rename:true,theme:'light',controlled_verified:false,controlled_actions:[],last_scan:'',scanned:0},suggested:[],token:'',plans:[],cleanup:[],sessions:[],errors:[],totals:{scanned:0,organized:0,cleanup_size:0,needs_review:0,ready:0,analyzed:0,already_organized:0,protected:0,protected_trees:0,projects:0,cleanup_candidates:0,unchanged:0}};
const api=window.organizer;
const size=(n:number)=>n>=1073741824?`${(n/1073741824).toFixed(1)} GB`:n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
function App(){
 const [data,setData]=useState(empty),[screen,setScreen]=useState('home'),[busy,setBusy]=useState(''),[progress,setProgress]=useState<Progress>({stage:'Preparing',current:0,total:0,file:''}),[paused,setPaused]=useState(false),[message,setMessage]=useState(''),[modal,setModal]=useState(''),[sessionId,setSessionId]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{api?.snapshot().then(setData).catch(e=>setMessage(String(e)));return api?.onProgress(setProgress);},[]);
 useEffect(()=>{const theme=data.settings.theme;document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;},[data.settings.theme]);
 const run=async(kind:string,operation:()=>Promise<Snapshot>,done?:(s:Snapshot)=>void)=>{if(busy)return;setBusy(kind);setMessage('');setPaused(false);setProgress({stage:'Preparing',current:0,total:0,file:''});try{const next=await operation();setData(next);if(next.restore_errors?.length)setMessage(next.restore_errors.join(' • '));done?.(next);}catch(e){setMessage(String(e).replace(/^Error: /,''));}finally{setBusy('');setPaused(false);}};
 const scan=()=>api?run('scan',()=>api.scan(),s=>setScreen(s.cancelled?'home':'scan')):setMessage('Open the Windows desktop app to scan local files.');
 const organize=()=>api&&run('organize',()=>api.organizeAll(data.token),s=>{setSessionId(s.sessions[0]?.id||'');setScreen('result');});
 const session=data.sessions.find(s=>s.id===sessionId)||data.sessions[0];
 const external=(operation:()=>Promise<unknown>)=>operation().catch(e=>setMessage(String(e)));
 const undo=(id:string)=>api&&run('undo',()=>api.restore(id));
 const option=(value:Record<string,unknown>)=>api&&run('settings',()=>api.options(value));
 const control=(action:string)=>api&&external(async()=>{await api.scanControl(action);if(action!=='cancel')setPaused(action==='pause');});
 const metrics=(rows:[string,string|number][])=> <div className="v2-metrics">{rows.map(([label,value])=><div key={label}><span>{label}</span><strong>{typeof value==='number'?value.toLocaleString():value}</strong></div>)}</div>;
 const sessionButtons=(id:string,report:string,undone:boolean)=> <div className="v2-actions"><button className="button secondary" onClick={()=>api&&external(()=>api.openFiles(id))}><FolderOpen size={16}/> Open Organized Files</button><button className="button secondary" disabled={!report} onClick={()=>api&&external(()=>api.viewReport(id))}><FileText size={16}/> View Word Report</button><button className="button text" disabled={undone} onClick={()=>undo(id)}><Undo2 size={16}/> Undo Organization</button></div>;
 return <div className="v2-shell"><header className="v2-header"><button className="v2-brand" onClick={()=>setScreen('home')}><span className="brand-mark"><Layers size={21}/></span>Smart File Organizer<span className="v2-version">ALPHA</span></button><div className="v2-header-actions"><span className="privacy-badge"><ShieldCheck size={14}/> Local. Private. Yours.</span><button className="icon-button" aria-label="Organization history" onClick={()=>setModal('history')}><Clock3 size={19}/></button><button className="icon-button" aria-label="Settings" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div></header><div className="v2-content">{message&&<div role="alert" className="notice">{message}<button className="icon-button" aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {screen==='home'&&<><section className="v2-hero"><div className="eyebrow"><Sparkles size={14}/> A LITTLE ORDER. A LITTLE MORE ROOM.</div><h1>Your computer,<br/>organized.</h1><p>A thoughtful home for your scattered files.<br/>Two clicks. Everything stays on your computer.</p><button className="button primary large" onClick={data.ready?organize:scan}><ScanLine size={19}/>{data.ready?'Organize Files':'Scan Computer'}<ArrowRight size={17}/></button><div className="hero-footnote">Protected areas are excluded. Session Undo is available.</div><div className="folder-art v2-art" aria-hidden="true"><div className="orbit-ring"/><div className="art-note note-back"><FileText size={29}/><div/><div/></div><div className="art-note note-front"><ImageIcon size={29}/><div/><div/></div><div className="art-folder"><div className="folder-tab"/><FolderOpen size={66} strokeWidth={1.1}/><span>Everything in its place</span></div><div className="art-badge"><Check size={14}/> Room for what matters</div></div></section>{metrics([['Files found',data.settings.last_scan?data.totals.scanned:'—'],['Files organized',data.totals.organized||'—'],['Cleanup potential',data.settings.last_scan?size(data.totals.cleanup_size):'—']])}<div className="v2-last"><Clock3 size={14}/> Last scan <span>{data.settings.last_scan?new Date(data.settings.last_scan).toLocaleString():'Never'}</span></div></>}
 {screen==='scan'&&<><section className="v2-intro"><span className="v2-status"><CheckCircle2 size={16}/> Scan complete</span><h1>A clearer picture.<br/>A place for the mess.</h1><p>We found your personal files and kept existing organization intact.<br/>Safe changes are ready. Uncertain files stay where they are.</p></section>{metrics([['Files analyzed',data.totals.analyzed],['Ready to organize',data.totals.ready],['Already organized',data.totals.already_organized],['Protected files found',data.totals.protected],['Protected trees skipped',data.totals.protected_trees],['Projects protected',data.totals.projects],['Cleanup candidates',data.totals.cleanup_candidates],['Potential cleanup',size(data.totals.cleanup_size)],['Uncertain files',data.totals.unchanged]])}<div className="v2-callout"><ShieldCheck size={21}/><p>Cleanup extras go to <strong>Review Before Delete</strong>. Nothing is permanently deleted. System, application and project folders stay untouched.</p></div><div className="v2-primary-row"><button className="button primary large" disabled={!data.ready||(!data.totals.ready&&!data.totals.cleanup_candidates)} onClick={organize}>Organize Files <ArrowRight size={18}/></button><button className="button text" onClick={()=>setModal('details')}><Search size={15}/> View Details</button><button className="button text" onClick={scan}>Scan Again</button></div>{data.errors.length>0&&<p className="v2-note">{data.errors.length} scan warnings. Files with unavailable text retain conservative names.</p>}</>}
 {screen==='result'&&session&&<><section className="v2-intro"><div className="v2-success"><CheckCircle2 size={37}/></div><h1>{session.undone?'Your originals are back.':session.failures.length?'Organization finished.':'Your files are organized.'}</h1><p>{session.undone?'This session has been restored to the original locations.':'A little less clutter. A little more clarity.'}</p></section>{metrics([['Files organized',session.organized],['Files renamed',session.renamed],['Folders created',session.folders_created],['Cleanup set aside',session.quarantined||0],['Potential cleanup',size(session.cleanup_size)],['Changes needing review',session.failures.length]])}{session.failures.length>0&&<div role="alert" className="notice">{session.failures.length} files were left unchanged or need review. See the report and session history.</div>}{session.report_error&&<div role="alert" className="notice">Files are logged. Report creation failed: {session.report_error}<button className="button text" onClick={()=>api&&run('report',()=>api.generateReport(session.id))}>Retry Report</button></div>}{sessionButtons(session.id,session.report,session.undone)}<button className="button primary large" onClick={()=>setScreen('home')}>Done <Check size={17}/></button><p className="v2-note">No personal files were permanently deleted. Cleanup bytes are set aside, not freed.</p></>}
 <p className="v2-note">Alpha software. Back up important files and test with non-critical data first.</p><footer className="v2-footer"><ShieldCheck size={13}/> Session history and Undo.<span>0.2.0-alpha</span></footer></div>
 {modal&&<div className="modal-backdrop"><section className="settings-modal v2-modal" role="dialog" aria-modal="true" aria-label={modal}><div className="section-top"><h2>{modal==='settings'?'Keep it simple.':modal==='history'?'Every change, saved.':'Your scan, in detail.'}</h2><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal('')}><X size={19}/></button></div>
 {modal==='settings'&&<><p>A few preferences. Safety protections always apply.</p><label>ORGANIZATION LOCATION</label><div className="library-choice"><FolderOpen size={20}/><span>{data.settings.library||'File Library'}</span><button className="button secondary" onClick={()=>api&&run('settings',()=>api.selectLibrary())}>Change</button></div><p className="v2-note">Other drives use their own File Library for safe same-volume moves.</p><div className="v2-setting"><span>Automatic rename<small>Only names supported by strong evidence</small></span><input type="checkbox" aria-label="Automatic rename" checked={data.settings.automatic_rename} onChange={e=>option({automatic_rename:e.target.checked})}/></div><div className="v2-setting"><span>Scan external drives<small>Accessible local storage only</small></span><input type="checkbox" aria-label="Scan external drives" checked={data.settings.external_drives} onChange={e=>option({external_drives:e.target.checked})}/></div><div className="v2-setting"><span>Theme</span><select aria-label="Theme" value={data.settings.theme} onChange={e=>option({theme:e.target.value})}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></div><h3 className="v2-subtitle">Drives</h3>{data.storage.filter(s=>s.drive).map(s=><div className="v2-setting" key={s.path}><span><HardDrive size={14}/> {s.name}</span><input aria-label={'Include drive '+s.path} type="checkbox" checked={!data.settings.excluded_drives.includes(s.path)} onChange={e=>option({excluded_drives:e.target.checked?data.settings.excluded_drives.filter(p=>p!==s.path):[...data.settings.excluded_drives,s.path]})}/></div>)}{!data.storage.some(s=>s.drive)&&<p className="v2-note">Drive preferences appear after your first scan.</p>}<h3 className="v2-subtitle">Excluded folders</h3>{data.settings.ignored.map(p=><div className="v2-setting" key={p}><small>{p}</small><button className="icon-button" aria-label={'Include '+p} onClick={()=>option({ignored:data.settings.ignored.filter(v=>v!==p)})}><X size={14}/></button></div>)}<button className="button secondary" onClick={()=>api&&run('settings',()=>api.excludeFolder())}>Exclude Folder</button><p className="v2-note">Changing preferences requires a new scan.</p></>}
 {modal==='details'&&<><p>Optional inspection. Safe files are organized together with one click.</p><input className="v2-search" aria-label="Find a file" placeholder="Find a file…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="v2-note">Showing up to 500 file records of {data.plan_count.toLocaleString()}. Complete operations are recorded locally.</p><div className="v2-detail-list">{data.plans.filter(p=>p.file.toLowerCase().includes(query.toLowerCase())).map(p=><div className="v2-detail" key={p.id}><div><strong>{p.file}</strong><span className="tag neutral">{p.status}</span></div><small>{p.reason}</small><p>{p.destination||p.source}</p></div>)}</div><h3 className="v2-subtitle">Storage safety</h3>{data.storage.map((s,i)=><div className="v2-setting" key={i}><small>{s.name}</small><span className="tag neutral">{s.kind}</span></div>)}</>}
 {modal==='history'&&<>{!data.sessions.length?<div className="quiet-empty">Your sessions and Word reports will appear here.</div>:data.sessions.map(s=><article className="v2-history" key={s.id}><div className="section-top"><strong>{new Date(s.created).toLocaleString()}</strong><span className="tag neutral">{s.undone?'Restored':'Recorded'}</span></div><p>{s.organized} files organized · {s.renamed} renamed</p>{sessionButtons(s.id,s.report,s.undone)}<details><summary>Operation details</summary>{s.actions.map(a=><div className="v2-detail" key={a.id}><strong>{a.status}</strong><p>{a.source} → {a.destination}</p>{a.error&&<small>{a.error}</small>}</div>)}</details></article>)}</>}
 </section></div>}
 {busy&&<div className="progress-backdrop"><div className="progress-card" role="status"><div className="progress-symbol"><LoaderCircle className={paused?'':'spin'} size={30}/></div><div className="eyebrow">{paused?'SCAN PAUSED':busy==='scan'?'A CLEARER PICTURE':'EVERY CHANGE IS SAVED'}</div><h2>{paused?'Take your time.':progress.stage}</h2><p>{busy==='scan'?'Finding the mess. Protecting what matters.':'Working carefully, one file at a time.'}</p><div className={'progress-track '+(!progress.total?'indeterminate':'')}><div style={{width:progress.total?`${Math.max(2,progress.current/progress.total*100)}%`:'25%'}}/></div><div className="progress-meta"><span>{progress.current.toLocaleString()} {progress.total?`of ${progress.total.toLocaleString()}`:'files discovered'}</span><span>{progress.total?`${Math.round(progress.current/progress.total*100)}% of this stage`:'Discovering…'}</span></div><span className="current-file">{progress.file}</span>{busy==='scan'&&<div className="v2-actions"><button className="button secondary" onClick={()=>control(paused?'resume':'pause')}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'Resume Scan':'Pause Scan'}</button><button className="button text" onClick={()=>control('cancel')}>Cancel Scan</button></div>}<div className="progress-safe"><ShieldCheck size={13}/> {busy==='scan'?'Read-only scan. No files are changed.':'Nothing deleted or overwritten.'}</div></div></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
